
export const ABOUT_SECTION_PROJECT_LIST: string[] = [
  'Go Home Come Back (Plan-B Theatre Company - World Premiere)',
  'The Tales of Hoffmann (Utah Valley University)',
  'My Brother was a Vampire (Plan-B Theatre Company - World Premiere)',
  'Tomás and the Library Lady (Theatre for Youth and Education Center - Touring Production)',
  'O Dear Blossom, A Dance Film (Scott Cook Productions, BYU Dance Department)',
  'Rusalka (Utah Vocal Arts Academy Summer Opera Festival)',
  'Macbeth Redux (Renaissance Now Theatre & Film)',
  'Much Ado About Nothing (Renaissance Now Theatre & Film)',
  'Aftershock (Plan-B Theatre Company - World Premiere)',
  'Charlotte’s Web (Theatre for Youth and Education Center - Touring Production)',
  'The Clean-Up Project (Plan-B Theatre Company - World Premiere)',
  'La Bohème (The Noorda Center for the Performing Arts)',
  'James and the Giant Peach (Utah Valley University)',
  'The Heidi Chronicles (Utah Valley University)',
  'The Tempest (Renaissance Now Theatre & Film)',
  'The Diaries of Romeo and Juliet (Renaissance Now Theatre & Film)',
  'Cinderella Eats Rice and Beans (Theatre for Youth and Education Center - Filmed Production)',
  'Festival of the Seas (Loveland Living Planet Aquarium)',
  'Last Train to Nibroc (An Other Theater Company)',
  'Timmon and the Magic Shoes (Theatre for Youth and Education Center - Filmed Production)',
  'Noises Off (Utah Valley University)',
  'Unchanged Voices (Utah Valley University - Devised Production)',
  'Urinetown: The Musical (Utah Valley University)',
  'Sweeney Todd: The Demon Barber of Fleet Street (The Noorda Center for the Performing Arts)',
  'Taming of the Shrew (Utah Valley University)',
  'Mr. Burns, A Post-Electric Play (An Other Theater Company)',
  'Mamma Mia! (Sundance Summer Theatre)',
  'The Laramie Project (Utah Valley University)',
  'A History of Breathing (Utah Valley University)',
  'Cabaret (Utah Valley University)',
  'The Drag (An Other Theater Company)',
  'Next Fall (An Other Theater Company)',
  'Agamemnon (Utah Valley University)',
  'Tribes (Utah Valley University)',
  'Fat Pig (An Other Theater Company)',
  'A Year with Frog and Toad (Utah Valley University)',
  'Joseph and the Technicolor Dreamcoat (Sundance Summer Theatre)',
  'The Taming of the Shrew (Renaissance Now Theatre & Film)',
  'Short Attention Span Theatre (Utah Valley University)',
  'Hamlet (Brigham Young University)',
];
